- name : Configure Docker on EC2 Instances
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name: updating apt
    command : sudo apt-get update

  - name : Install Docker
    command : sudo apt-get install -y docker.io

  - name : Start Docker Service
    command : sudo systemctl start docker
    
  - name: Create insureme directory
    file:
      path: /home/devops/insureme
      state: directory
      owner: devops
      group: devops
      mode: '0755'
      
  - name: Copy application code to remote
    copy:
      src: /home/devops/workspace/insureme/   # Path on Jenkins/Ansible control node
      dest: /home/devops/insureme                    # Path on target machine
      owner: devops
      group: devops
      mode: '0755'
      
  - name : Stop old container
    command : sudo docker stop my-insurance-app-container
    ignore_errors: yes

  - name : Remove old containers
    command : sudo docker rm my-insurance-app-container
    ignore_errors: yes
  
  - name : Build the docker image
    command : sudo docker build -t chikara123/insurance-prj:v1.0 /home/devops/

  - name: Deploy Docker Container
    command : sudo docker run -d --name my-insurance-app-container -p 8082:8081 chikara123/insurance-prj:v1.0
